version: "3.7"
services:
  react-dev:
    container_name: react-dev
    image: shuvro/tic-tac-toe-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development